name: ParkourBeat
main: ru.sortix.parkourbeat.ParkourBeat
version: 0.5
author: Sortix, Bomb
depend: [AMusic]
commands:
  tptoworld:
  play:
  editor:


    ###Вывести команды в главный класс для инициализации и/или создать отдельный, чтобы не вписывать их в конфигурацию.
    ### Конфигурацию с руссификацией и прочими языками, можно вынести в ../resources/translations/ru_RU.properties
    ### Удалите файл lang.yml и проведите путь к ../resources/translations/ru_RU.properties